name: selective-long-range-connection-gnn
channels:
  - pyg
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=2.0.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - atk-1.0=2.36.0
  - attrdict=2.0.1
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.7.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cachetools=5.3.2
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - dgl=1.1.3
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - future=0.18.3
  - gdk-pixbuf=2.42.10
  - giflib=5.2.1
  - glib=2.69.1
  - gobject-introspection=1.72.0
  - google-auth=2.25.2
  - google-auth-oauthlib=1.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.4.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lightning-utilities=0.9.0
  - lz4-c=1.9.4
  - markdown=3.5.1
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.4
  - pango=1.50.7
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.40.0
  - platformdirs=4.1.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.41
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyg=2.4.0
  - pygments=2.17.2
  - pygraphviz=1.9
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tensorboard=2.15.1
  - tensorboard-data-server=0.7.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchmetrics=1.1.2
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - wcwidth=0.2.12
  - werkzeug=3.0.1
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torch-tb-profiler==0.4.3
